server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:192.168.1.12:9092}
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest

logging:
  level:
    org:
      apache:
        kafka: OFF 